<?php
namespace frontend\controllers;

use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\models\Articols;

class ArticolsController extends Controller
{
    public function beforeAction($action)
    {
        return true; // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => \yii\filters\VerbFilter::className(),
                'actions' => [
                    'index'  => ['GET', 'POST', 'RANDOM','DELETE'],
                ],
            ],
        ];
    }
    //get все статьи
    public function actionArticols()
    {   //проверка на get запрос
        if(Yii::$app->request->isGet) {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $articols = Articols::find()->all();
            return $articols;
        }
        else if(Yii::$app->request->isPost)
        {
            return "post";
        }
    }
    //get одну статью
    public function actionArticol()
    {   //проверка на get запрос
        if(Yii::$app->request->isGet) {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $articol = Articols::find()->where(['id' => yii::$app->request->get()['id']])->one();
            return $articol;
        }
    }


    public function actionCreate()
    {
        if(Yii::$app->request->isPost) {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $articol = new Articols();
            $articol->title = yii::$app->request->get()['title'];
            $articol->text = yii::$app->request->get()['text'];
            $articol->author_id = yii::$app->request->get()['author_id'];

            $articol->save();
            return $articol;
        }
    }
    public function actionDelete()
    {
         if(Yii::$app->request->isDelete)
         {
             \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
             $articol =Articols::find()->where(['id'=>yii::$app->request->get()['id']])->one();
             $articol->delete();
             return $articol;
         }
    }
//    public function  actionCheck_metod()
//    {
//        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
//        $method = get_method();
//        if (\Yii::$app->request->isGet) {
//            return "get";
//        } elseif (\Yii::$app->request->isPost) {
//            return "post";
//
//        } elseif ($method === 'RANDOM') {
//            return "random";
//
//        } else {
//            return "not fount";
//
//        }
//    }


}
