<?php

namespace frontend\controllers;

use yii\web\Controller;

class TestController extends Controller
{
    public function beforeAction($action)
    {
        return true; // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => \yii\filters\VerbFilter::className(),
                'actions' => [
                    'index'  => ['GET', 'POST', 'RANDOM'],
                ],
            ],
        ];
    }

    public function actionTest()
    {
        $method = get_method();
        if ($method === 'GET') {
            var_dump($method);
        } elseif ($method === 'POST') {
            var_dump($method);

        } elseif ($method === 'RANDOM') {
            var_dump($method);

        } else {
            var_dump('no');

        }
    }

}
